### ISSUE TITLE
Github icon overlaps Picture

### ISSUE THREAD

**Issue by aribeller** [tobiasgerstenberg/homepage#25]
When in fullscreen mode, if you hover over the github icon for some lab members it overlaps the picture. Relatedly, different people seem to have different margins between their pictures and their icons. It would be good to make it so that everyone has the same spacing and there is no overlap.

**Comment by aribeller** [comment]
I traced this to the css. The .social-links class has a small margin-top value (1pt) which would probably explain the closeness. I'm struggling getting a fix though. For some reason when I modify the custom.css file in static/css it is not registering the change in public/css. Maybe something weird about overriding?

**Comment by tobiasgerstenberg** [comment]
it seems to have worked in my case. i added a little bit more space to the .social-links object

**Comment by aribeller** [comment]
Weird. Maybe it was a chrome caching issue. I'll close the issue
